server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: sccpcm2012
    url: jdbc:postgresql://localhost:5432/curso_springcloud
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
